export const coins = [
  "Bitcoin (BTC)",
  "Ethereum (ETH)",
  "Tether (USDT)",
  "BNB (BNB)",
  "Solana (SOL)",
  "XRP (XRP)",
  "Cardano (ADA)",
  "USD Coin (USDC)",
  "Dogecoin (DOGE)",
  "Polkadot (DOT)",
  "Avalanche (AVA)",
  "Chainlink (LIN)",
  "Litecoin (LTC)",
  "Bitcoin Cash (BHC)",
  "Stellar (XLM)",
  "Uniswap (UNI)",
  "ApeCoin (APE)",
  "Cosmos (ATOM)",
  "TRON (TRX)",
  "Monero (XMR)",
  "Ethereum Classic (ETC)",
  "Algorand (ALGO)",
  "Dash (DASH)",
  "VeChain (VET)",
  "Tezos (XTZ)",
  "Zcash (ZEC)",

  "USD Coin (USDC)",
  "VeChain (VET)",
  "Verge (XVG)",
  "Waves (WAVES)",
  "Yearn.finance ",
  "Zilliqa (ZIL)",
  "Zcash (ZEC)",
  "Covalent (CQT)",
  "Crust Network ",
  "Curve DAO Toke",
  "CyberVein (CVT)",
];
